spring:
  config:
    import: classpath:secret.yml

  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mysql://localhost:3306/moamoa
    username: root
    password: ${moamoa.datasource.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  cache:
    cache-names:
      - memoryExchangeRates
      - redisExchangeRates

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  access-token:
    expiration: 99999999
  refresh-token:
    expiration: 99999999

server:
  port: 8070
